// <auto-generated />
using E_Shop_Catalog.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace E_Shop_Catalog.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20231209115324_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("E_Shop_Catalog.Model.ComputerModel", b =>
                {
                    b.Property<int>("Computers_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Computers_Id"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GPY")
                        .HasColumnType("integer");

                    b.Property<string>("Graphic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Proccesor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity_Ram")
                        .HasColumnType("integer");

                    b.Property<string>("Ram_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ram_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Computers_Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("E_Shop_Catalog.Model.LaptopModel", b =>
                {
                    b.Property<int>("Laptops_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Laptops_Id"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GPY")
                        .HasColumnType("integer");

                    b.Property<string>("Graphic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Monitor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Proccesor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity_Ram")
                        .HasColumnType("integer");

                    b.Property<string>("Ram_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ram_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Laptops_Id");

                    b.ToTable("Laptops");
                });

            modelBuilder.Entity("E_Shop_Catalog.Model.ProductModel", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Product_Id"));

                    b.Property<int>("Category_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Product_Id");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
